services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '3000:5432'
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql/data