"""Created_at was added

Revision ID: d59a1c2c868a
Revises: 93566f5f48a9
Create Date: 2024-11-01 08:46:55.022728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59a1c2c868a'
down_revision: Union[str, None] = '93566f5f48a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'created_at')
    # ### end Alembic commands ###
